version: "3.8"
services:
  web:
    build: ./app
    image: 832520132844.dkr.ecr.us-east-1.amazonaws.com/docker_docker_aws_ec2:project_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DB_NAME=restaurant_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=restaurant.cnuqriqxhc95.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-34-236-188-110.compute-1.amazonaws.com
    nginx:
      build: ./nginx
      image: 832520132844.dkr.ecr.us-east-1.amazonaws.com/docker_docker_aws_ec2:project_nginx
    depends_on:
      - pg

  pg:
    container_name: pg_container
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: restaurant_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./data/misc/django_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - pg