# Generated by Django 3.2.2 on 2022-02-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
